name: "Deploy Admin Panel to dev"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-admin:
    uses: ./.github/workflows/deploy-admin.yml
    with:
      environment: 'prod'
    secrets:
      IAM_WORKFLOW_ROLE: ${{ secrets.DEV_IAM_WORKFLOW_ROLE }}